Performing Lookalike

In [10]:
# importing libraies 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn

In [11]:
# Read the CSV files into dataframes
Customers_df = pd.read_csv(r"C:\Users\Lenovo\Downloads\data science intern\Customers.csv")
transactions_df = pd.read_csv(r"C:\Users\Lenovo\Downloads\data science intern\Transactions.csv")
products_df = pd.read_csv(r"C:\Users\Lenovo\Downloads\data science intern\Products.csv")

# Display the first few rows of each dataframe to understand their structure
products_df.head(), Customers_df.head()

(  ProductID              ProductName     Category   Price
 0      P001     ActiveWear Biography        Books  169.30
 1      P002    ActiveWear Smartwatch  Electronics  346.30
 2      P003  ComfortLiving Biography        Books   44.12
 3      P004            BookWorld Rug   Home Decor   95.69
 4      P005          TechPro T-Shirt     Clothing  429.31,
   CustomerID        CustomerName         Region  SignupDate
 0      C0001    Lawrence Carroll  South America  2022-07-10
 1      C0002      Elizabeth Lutz           Asia  2022-02-13
 2      C0003      Michael Rivera  South America  2024-03-07
 3      C0004  Kathleen Rodriguez  South America  2022-10-09
 4      C0005         Laura Weber           Asia  2022-08-15)

In [12]:
# merging the files
# Merge transactions with products
transactions_products = transactions_df.merge(products_df, on="ProductID", how="left")

# Merge the resulting DataFrame with customers
final_merged_df = transactions_products.merge(Customers_df, on="CustomerID", how="left")
final_merged_df

,TransactionID,CustomerID,ProductID,TransactionDate,Quantity,TotalValue,Price_x,ProductName,Category,Price_y,CustomerName,Region,SignupDate
0,T00001,C0199,P067,2024-08-25 12:38:23,1,300.68,300.68,ComfortLiving Bluetooth Speaker,Electronics,300.68,Andrea Jenkins,Europe,2022-12-03
1,T00112,C0146,P067,2024-05-27 22:23:54,1,300.68,300.68,ComfortLiving Bluetooth Speaker,Electronics,300.68,Brittany Harvey,Asia,2024-09-04
2,T00166,C0127,P067,2024-04-25 07:38:55,1,300.68,300.68,ComfortLiving Bluetooth Speaker,Electronics,300.68,Kathryn Stevens,Europe,2024-04-04
3,T00272,C0087,P067,2024-03-26 22:55:37,2,601.36,300.68,ComfortLiving Bluetooth Speaker,Electronics,300.68,Travis Campbell,South America,2024-04-11
4,T00363,C0070,P067,2024-03-21 15:10:10,3,902.04,300.68,ComfortLiving Bluetooth Speaker,Electronics,300.68,Timothy Perez,Europe,2022-03-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,T00496,C0118,P037,2024-10-24 08:30:27,1,459.86,459.86,SoundWave Smartwatch,Electronics,459.86,Jacob Holt,South America,2022-01-22
996,T00759,C0059,P037,2024-06-04 02:15:24,3,1379.58,459.86,SoundWave Smartwatch,Electronics,459.86,Mrs. Kimberly Wright,North America,2024-04-07
997,T00922,C0018,P037,2024-04-05 13:05:32,4,1839.44,459.86,SoundWave Smartwatch,Electronics,459.86,Tyler Haynes,North America,2024-09-21
998,T00959,C0115,P037,2024-09-29 10:16:02,2,919.72,459.86,SoundWave Smartwatch,Electronics,459.86,Joshua Hamilton,Asia,2024-11-11
999,T00992,C0024,P037,2024-04-21 10:52:24,1,459.86,459.86,SoundWave Smartwatch,Electronics,459.86,Michele Cooley,North America,2024-02-05

In [14]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

In [15]:
features = final_merged_df.groupby("CustomerID").agg({
    "TotalValue": "sum",               # Total spending
    "Quantity": "sum",                 # Total quantity purchased
    "ProductID": "nunique"             # Number of unique products purchased
}).reset_index()
features

    CustomerID  TotalValue  Quantity  ProductID
0        C0001     3354.52        12          5
1        C0002     1862.74        10          4
2        C0003     2725.38        14          4
3        C0004     5354.88        23          8
4        C0005     2034.24         7          3
..         ...         ...       ...        ...
194      C0196     4982.88        12          3
195      C0197     1928.65         9          3
196      C0198      931.83         3          2
197      C0199     1979.28         9          4
198      C0200     4758.60        16          5

[199 rows x 4 columns]

In [18]:
#  Normalize the features
scaler = StandardScaler()
normalized_features = scaler.fit_transform(features.iloc[:, 1:])  # Exclude CustomerID
normalized_features

array([[-0.06170143, -0.12203296,  0.05004655],
       [-0.87774353, -0.44800021, -0.42420409],
       [-0.40585722,  0.20393428, -0.42420409],
       [ 1.03254704,  1.67078689,  1.47279848],
       [-0.78392861, -0.93695108, -0.89845473],
       [ 0.41587942, -0.12203296, -0.42420409],
       [-0.48548229, -0.77396745, -0.89845473],
       [ 0.43997044,  1.18183602,  2.42129976],
       [-1.40630171, -1.58888557, -0.89845473],
       [-0.9571662 , -0.12203296, -0.42420409],
       [ 0.14369581,  0.04095066,  0.05004655],
       [ 0.96492372,  1.0188524 ,  0.52429719],
       [ 1.38575064,  0.85586877,  0.99854783],
       [-1.72239508, -1.75186919, -1.84695602],
       [-1.26353893, -1.42590195, -1.37270538],
       [ 0.22269727, -0.44800021,  0.05004655],
       [ 0.70375173,  1.34481964,  1.47279848],
       [ 0.71908486,  0.85586877,  0.05004655],
       [-0.70101045, -0.28501659,  0.52429719],
       [-1.39212827, -1.58888557, -1.84695602],
       [ 1.0681256 ,  0.69288515,  1.47279848],
       [ 0.64973294,  0.3669179 ,  0.52429719],
       [ 0.92520418,  0.20393428,  0.52429719],
       [ 0.08736309,  0.20393428,  0.99854783],
       [-1.02704328, -0.77396745, -0.42420409],
       [ 0.04471149, -0.12203296, -0.42420409],
       [-0.49471609, -0.12203296, -0.42420409],
       [ 1.83377022,  1.83377051,  0.52429719],
       [-0.9197934 , -0.44800021, -0.42420409],
       [-0.50196965,  0.04095066,  0.05004655],
       [-0.79971578, -0.44800021, -0.42420409],
       [-1.52856197, -1.26291832, -0.89845473],
       [-1.82415282, -1.75186919, -1.84695602],
       [-0.21559072,  0.69288515,  0.52429719],
       [-0.48122096, -0.44800021, -0.42420409],
       [-0.8694178 , -0.77396745, -0.89845473],
       [ 0.42966447,  0.20393428,  0.05004655],
       [-0.42146387,  0.04095066,  0.05004655],
       [ 0.42246014,  0.85586877,  0.52429719],
       [ 0.27465378, -0.44800021, -1.37270538],
       [ 1.46737783,  1.67078689,  0.99854783],
       [-0.58248637, -1.0999347 , -0.89845473],
       [-1.27784912, -1.0999347 , -0.89845473],
       [-0.1297569 , -0.93695108, -0.89845473],
       [ 1.39736947,  1.67078689,  0.99854783],
       [ 1.18185773,  1.0188524 ,  0.99854783],
       [-0.32645096,  0.04095066,  0.99854783],
       [ 0.2098531 , -0.12203296,  0.05004655],
       [-0.63008308,  0.69288515,  1.47279848],
       [-0.21798122, -0.77396745, -0.89845473],
       [ 1.22110135,  0.52990153,  0.99854783],
       [-0.53570473, -0.44800021, -0.89845473],
       [ 1.01153031,  0.85586877,  0.52429719],
       [ 2.50159022,  1.83377051,  1.47279848],
       [-0.33348571, -0.12203296,  0.05004655],
       [-0.15556011, -0.12203296,  0.05004655],
       [ 0.58481739,  0.52990153,  0.52429719],
       [-1.67990212, -1.91485281, -1.84695602],
       [ 1.97255613,  1.34481964,  1.47279848],
       [-1.85165727, -1.75186919, -1.84695602],
       [-0.72702699, -1.0999347 , -0.89845473],
       [-0.99983968, -0.77396745, -1.37270538],
       [-1.14281581, -1.26291832, -1.37270538],
       [ 0.31314798,  0.04095066,  0.05004655],
       [ 2.29553108,  2.32272138,  2.42129976],
       [ 0.18159375, -0.61098383, -0.89845473],
       [ 0.34108459,  0.20393428,  0.52429719],
       [ 1.35832277,  1.50780326,  1.47279848],
       [-0.3219927 , -0.44800021,  0.05004655],
       [-0.18698674, -0.12203296, -0.42420409],
       [-1.13042021, -0.93695108, -0.89845473],
       [-0.25585728,  0.04095066,  0.05004655],
       [-0.76954183, -0.44800021, -0.89845473],
       [-0.22542624, -0.77396745, -0.89845473],
       [ 1.302827  ,  2.485705  ,  1.94704912],
       [-0.62046637, -0.28501659,  0.05004655],
       [-1.43868564, -0.93695108, -0.89845473],
       [-1.35213522, -1.75186919, -1.84695602],
       [ 0.42900257, -0.12203296, -0.42420409],
       [-1.34557091, -1.58888557, -1.84695602],
       [ 0.04111754,  0.20393428,  0.52429719],
       [ 2.24586661,  1.67078689,  0.99854783],
       [-1.54508215, -1.42590195, -0.89845473],
       [ 0.53268583,  1.18183602,  1.47279848],
       [-0.47535685, -0.93695108, -0.89845473],
       [-0.38982937,  0.04095066,  0.05004655],
       [ 1.71597369,  1.50780326,  0.99854783],
       [-0.72860243, -0.44800021,  0.05004655],
       [-0.4983921 , -0.93695108, -1.37270538],
       [ 0.36696985,  0.52990153,  0.99854783],
       [-0.18032944,  1.18183602,  0.05004655],
       [-0.24690794, -0.44800021, -0.89845473],
       [ 0.99978567,  1.0188524 ,  1.47279848],
       [-1.25834765, -0.61098383, -0.42420409],
       [-1.19418153, -1.26291832, -1.37270538],
       [ 1.42533343,  0.52990153,  0.05004655],
       [-1.82147239, -1.91485281, -1.84695602],
       [-0.16919199,  0.20393428,  1.47279848],
       [ 1.77696159,  1.34481964,  1.47279848],
       [ 0.84030578,  0.20393428,  0.52429719],
       [ 1.13982427,  1.18183602,  0.99854783],
       [ 1.45784864,  1.34481964,  0.99854783],
       [-0.549632  , -0.93695108,  0.05004655],
       [ 1.70222693,  1.34481964,  1.47279848],
       [ 0.73308872,  0.52990153,  0.52429719],
       [-0.28883747,  0.04095066,  0.05004655],
       [ 0.08566731, -0.12203296,  0.05004655],
       [ 0.75556601,  0.52990153,  0.99854783],
       [ 1.10495684,  3.13763949,  2.42129976],
       [-1.38123699, -1.42590195, -1.84695602],
       [-0.81741753,  0.52990153,  0.05004655],
       [-0.82480785, -0.77396745, -0.89845473],
       [ 0.73563239,  1.50780326,  0.99854783],
       [ 1.26533386,  0.85586877,  0.05004655],
       [-0.18059201, -0.77396745, -0.89845473],
       [-0.38764126, -0.28501659,  0.52429719],
       [ 0.30685718, -0.12203296, -0.42420409],
       [-0.01780261, -0.44800021,  0.52429719],
       [-1.24486894, -1.0999347 ,  0.05004655],
       [-0.54554572, -0.61098383, -0.89845473],
       [-1.36362276, -0.77396745, -0.42420409],
       [ 0.87810526,  0.69288515,  0.99854783],
       [-1.13084142, -1.42590195, -1.37270538],
       [ 0.43598809,  1.0188524 ,  0.99854783],
       [-0.26987756, -0.44800021, -0.42420409],
       [ 0.60077413,  0.04095066,  0.52429719],
       [-0.12824164, -0.28501659,  0.52429719],
       [-1.47375546, -1.58888557, -1.37270538],
       [-0.61688335, -0.61098383, -0.89845473],
       [-1.5677509 , -1.75186919, -1.84695602],
       [-0.83339068, -0.93695108, -0.89845473],
       [-0.88402339, -0.77396745, -1.37270538],
       [-0.31890748, -0.28501659, -0.42420409],
       [-0.43107511,  0.52990153,  0.05004655],
       [-0.18146725, -0.44800021, -0.42420409],
       [ 0.454948  ,  1.34481964,  0.52429719],
       [-0.07371958, -0.28501659,  0.05004655],
       [ 1.17224101,  0.69288515, -0.42420409],
       [ 0.12927621,  0.04095066,  1.47279848],
       [-0.86384908, -1.26291832, -1.37270538],
       [ 3.94217164,  2.32272138,  2.42129976],
       [-0.67189773, -0.28501659, -0.42420409],
       [ 1.40985807,  1.34481964,  0.52429719],
       [-1.18301673, -0.77396745, -1.37270538],
       [ 1.2603231 ,  1.18183602,  0.99854783],
       [-0.49041646, -0.77396745, -0.42420409],
       [-0.28383765,  0.20393428,  1.94704912],
       [ 1.08884146,  0.85586877,  0.05004655],
       [ 0.51281786,  0.3669179 ,  0.05004655],
       [-1.57924938, -1.75186919, -1.84695602],
       [-1.77419842, -1.42590195, -1.84695602],
       [-0.04455764, -0.44800021,  0.05004655],
       [ 0.69881209,  0.69288515,  0.52429719],
       [ 0.1292598 , -0.28501659,  0.52429719],
       [ 1.04510128,  0.69288515,  0.99854783],
       [ 2.27953058,  2.485705  ,  2.42129976],
       [-0.87043527, -0.44800021,  0.05004655],
       [ 0.1363219 , -0.61098383, -0.42420409],
       [-0.76304864, -0.77396745, -0.89845473],
       [-0.29560418,  0.20393428,  0.05004655],
       [-0.17804834,  0.20393428,  1.47279848],
       [ 0.73023872,  1.18183602,  1.47279848],
       [ 1.26251668,  1.0188524 ,  0.05004655],
       [-0.20766431, -0.44800021,  0.05004655],
       [ 1.77279325,  2.81167225,  0.52429719],
       [-0.58092188, -0.28501659, -0.42420409],
       [-0.63832129, -0.77396745, -0.89845473],
       [ 0.86786493, -0.12203296, -0.42420409],
       [ 0.58313255,  1.18183602,  0.52429719],
       [ 0.80107856,  0.3669179 ,  0.05004655],
       [ 0.91792873,  0.3669179 ,  0.05004655],
       [-0.69232368, -0.44800021,  0.52429719],
       [ 1.28043724,  1.18183602,  1.47279848],
       [-0.31473914, -0.12203296,  0.05004655],
       [ 1.50060964,  2.15973776,  2.42129976],
       [-0.6214182 , -0.12203296, -0.89845473],
       [-0.52377957, -0.61098383, -0.42420409],
       [-0.4149105 , -0.61098383, -0.42420409],
       [ 0.10148183,  0.20393428,  0.52429719],
       [-0.06548685,  0.3669179 ,  0.52429719],
       [ 0.82789923,  0.69288515,  0.05004655],
       [ 0.20945925, -0.12203296,  0.05004655],
       [-0.04055341, -0.28501659,  0.52429719],
       [-0.02351903, -0.61098383, -0.89845473],
       [-0.93304784, -0.93695108, -0.89845473],
       [ 0.62641323, -0.28501659,  0.05004655],
       [ 1.99336499,  1.34481964,  0.99854783],
       [-0.45080633, -0.28501659,  0.05004655],
       [-0.2649215 ,  0.20393428,  0.05004655],
       [-0.25674347, -0.28501659,  0.05004655],
       [-0.76287906, -0.77396745, -0.42420409],
       [-0.25055113, -0.28501659, -0.42420409],
       [ 0.21982538,  0.20393428,  0.99854783],
       [ 0.31123339,  0.69288515,  0.52429719],
       [ 0.82905346, -0.12203296, -0.89845473],
       [-0.84168906, -0.61098383, -0.89845473],
       [-1.38697529, -1.58888557, -1.37270538],
       [-0.81399315, -0.61098383, -0.42420409],
       [ 0.70636652,  0.52990153,  0.05004655]])

In [20]:
# Compute cosine similarity
similarity_matrix = cosine_similarity(normalized_features)

# Find top 3 lookalikes for the first 20 customers
customer_ids = features["CustomerID"].values
lookalike_dict = {}

Selecting first 20 customer id and then mapping it

In [21]:
for i, cust_id in enumerate(customer_ids[:20]):  # Only for the first 20 customers
    similarities = list(enumerate(similarity_matrix[i]))
    sorted_similarities = sorted(similarities, key=lambda x: x[1], reverse=True)[1:4]  # Exclude self
    lookalike_dict[cust_id] = [(customer_ids[j], round(score, 2)) for j, score in sorted_similarities]

# Step 5: Save the results to a CSV file
lookalike_df = pd.DataFrame({
    "CustomerID": lookalike_dict.keys(),
    "Recommendations": lookalike_dict.values()
})

In [22]:
lookalike_dict

{'C0001': [('C0164', np.float64(0.97)),
  ('C0137', np.float64(0.96)),
  ('C0069', np.float64(0.96))],
 'C0002': [('C0029', np.float64(1.0)),
  ('C0031', np.float64(1.0)),
  ('C0094', np.float64(0.99))],
 'C0003': [('C0176', np.float64(0.89)),
  ('C0027', np.float64(0.86)),
  ('C0010', np.float64(0.83))],
 'C0004': [('C0075', np.float64(1.0)),
  ('C0175', np.float64(0.99)),
  ('C0195', np.float64(0.99))],
 'C0005': [('C0058', np.float64(1.0)),
  ('C0123', np.float64(1.0)),
  ('C0015', np.float64(1.0))],
 'C0006': [('C0079', np.float64(1.0)),
  ('C0196', np.float64(0.99)),
  ('C0117', np.float64(0.99))],
 'C0007': [('C0140', np.float64(1.0)),
  ('C0085', np.float64(1.0)),
  ('C0125', np.float64(1.0))],
 'C0008': [('C0179', np.float64(1.0)),
  ('C0081', np.float64(0.99)),
  ('C0090', np.float64(0.99))],
 'C0009': [('C0192', np.float64(1.0)),
  ('C0177', np.float64(1.0)),
  ('C0083', np.float64(1.0))],
 'C0010': [('C0142', np.float64(0.96)),
  ('C0027', np.float64(0.96)),
  ('C0029', np.float64(0.96))],
 'C0011': [('C0023', np.float64(0.98)),
  ('C0064', np.float64(0.98)),
  ('C0100', np.float64(0.97))],
 'C0012': [('C0041', np.float64(1.0)),
  ('C0045', np.float64(1.0)),
  ('C0087', np.float64(0.99))],
 'C0013': [('C0059', np.float64(1.0)),
  ('C0141', np.float64(1.0)),
  ('C0105', np.float64(1.0))],
 'C0014': [('C0033', np.float64(1.0)),
  ('C0095', np.float64(1.0)),
  ('C0060', np.float64(1.0))],
 'C0015': [('C0131', np.float64(1.0)),
  ('C0058', np.float64(1.0)),
  ('C0005', np.float64(1.0))],
 'C0016': [('C0107', np.float64(0.96)),
  ('C0152', np.float64(0.85)),
  ('C0183', np.float64(0.83))],
 'C0017': [('C0162', np.float64(1.0)),
  ('C0124', np.float64(1.0)),
  ('C0084', np.float64(1.0))],
 'C0018': [('C0182', np.float64(0.98)),
  ('C0165', np.float64(0.98)),
  ('C0028', np.float64(0.98))],
 'C0019': [('C0172', np.float64(0.99)),
  ('C0116', np.float64(0.96)),
  ('C0056', np.float64(0.91))],
 'C0020': [('C0080', np.float64(1.0)),
  ('C0167', np.float64(1.0)),
  ('C0063', np.float64(1.0))]}

Saving the lookalike result into a csv file

In [24]:
lookalike_df.to_csv(" FirstName_LastName_Lookalike.csv", index=False)